AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided
    Handler: rust.binary
    Timeout: 3

Resources:
  GoogleAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bootstraps/auth
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GoogleAuthEndpoint:
          Type: Api
          Properties:
            Path: /auth
            Method: post
  ListCommentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bootstraps/list-comments
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GoogleAuthEndpoint:
          Type: Api
          Properties:
            Path: /commentable/{id}/comments
            Method: get
  CommentableRsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CommentableRsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: primary_key
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: primary_key
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
