AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided
    Handler: rust.binary
    Timeout: 3

Resources:
  GoogleAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bootstraps/auth
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GoogleAuthEndpoint:
          Type: Api
          Properties:
            Path: /auth
            Method: post
  ListCommentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bootstraps/list-comments
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GoogleAuthEndpoint:
          Type: Api
          Properties:
            Path: /commentable/{id}/comments/list
            Method: post
  AddCommentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bootstraps/add-comment
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GoogleAuthEndpoint:
          Type: Api
          Properties:
            Path: /commentable/{id}/comments/add
            Method: post
  DeleteCommentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bootstraps/delete-comment
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GoogleAuthEndpoint:
          Type: Api
          Properties:
            Path: /commentable/{id}/comments/delete
            Method: post
  CommentableRsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CommentableRsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: primary_key
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: primary_key
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: replies-index
          KeySchema:
            - AttributeName: primary_key
              KeyType: HASH
            - AttributeName: replies_to
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: reactions-index
          KeySchema:
            - AttributeName: primary_key
              KeyType: HASH
            - AttributeName: comment_id
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
