AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided
    Handler: rust.binary
    Timeout: 3

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bootstraps/auth
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GoogleAuthEndpoint:
          Type: Api
          Properties:
            Path: /auth
            Method: post
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
